# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# prompt format
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$buf\
$c\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

# Wait x milliseconds for starship to check files under the current directory.
scan_timeout = 30

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = "[➜](green)"
error_symbol = "[✗](red)"

[buf]
format = "with [$symbol($version)](green) "
symbol = "buf "

[directory]
read_only = " ro"
truncation_length = 2

[gcloud]
disabled = true

[nodejs]
symbol = "⬢ "

[package]
display_private = true

[sudo]
disabled = false
symbol = "👩💻 "
style = "bold red"

[username]
disabled = false
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
show_always = false
