#!/bin/sh

# exit on first non-zero exit
set -e

# bootstrap tmux
if type tmux  > /dev/null; then
  echo "bootstraping tmux..."
  # FIXME: this doesn't work on fresh machines
  # still need to open tmux and prefix + I (capital I to install)
  # install plugins
  # . "$HOME/.tmux/plugins/tpm/bin/install_plugins"
fi

# configure nnn
if type nnn > /dev/null; then
  # download buil-in plugins
  curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh
fi

# bootstrap nvim
if type nvim  > /dev/null; then
  echo "bootstraping nvim..."
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

# yadm bootstrap
if type yadm  > /dev/null; then
  echo "Updating the yadm repo origin to SSH"
  yadm remote set-url origin "git@github.com:enometsys/dotfiles.git"
fi
