#!/usr/bin/env bash

# Audio volume changer using alsa mixer

function cvol {
  bc <<< "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -d' ' -f2)*100" | cut -d '.' -f1
}

function chkmute {
  wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep MUTED
}

function notify {
  volume=`cvol`
  
  if [ "$volume" = "0" ]; then
    icon_name="audio-volume-muted-symbolic.symbolic"
  else    
    if [  "$volume" -lt "10" ]; then
      icon_name="audio-volume-low-symbolic.symbolic"
    else
      if [ "$volume" -lt "30" ]; then
        icon_name="audio-volume-low-symbolic.symbolic"
      else
        if [ "$volume" -lt "70" ]; then
          icon_name="audio-volume-medium-symbolic.symbolic"
        else
          icon_name="audio-volume-high-symbolic.symbolic"
        fi
      fi
    fi
  fi

  dunstify -r 1234 -i "$icon_name" -t 2000 "$volume "
}

case $1 in
  up)
	  # Unmute
    wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
	  # +5%
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
    # update statusbar
    . "$HOME/.scripts/check-status" update-statusbar
    # notify
	  notify
	;;
  down)
    # Unmute
    wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
    # -5%
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
    # update statusbar
    . "$HOME/.scripts/check-status" update-statusbar
    # notify
	  notify
	;;
  mute)
    # Toggle mute
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    # update statusbar
    . "$HOME/.scripts/check-status" update-statusbar
    # notify
	  if chkmute ; then
      icon_name="audio-volume-muted-symbolic.symbolic"
      dunstify -r 1234 -i "$icon_name" -t 2000 "Muted "
	  else
	    notify
	  fi
	;;
esac
