#!/bin/bash

SPACING="  "
DIVIDER="$SPACING|$SPACING"

function print_network {
  wifi_status=$( nmcli | grep -e '^wl.*:' | cut -d':' -f2 | sed -r 's/connected to//' )

  if [[ $wifi_status == "disconnected" ]]; then
    echo -e "offline$DIVIDER"
  elif [[ $wifi_status == "connected" ]]; then
    wifi_name=$( nmcli | grep -e 'wl.*0: conn' | cut -d' ' -f4 )
    echo -e "$wifi_name$DIVIDER"
  else
    echo -e "$wifi_status$DIVIDER"
  fi
}

function print_video {
  vendor=$( glxinfo | egrep 'OpenGL vendor' | cut -d':' -f2 | cut -d' ' -f2 )
  echo -e "$vendor$DIVIDER"
}

function print_mail {
  counter_file="/tmp/himalaya-counter"
  touch -a $counter_file
  unread=$( cat $counter_file )
  unread=${unread:-0}
  echo -e "Mail U:$unread$DIVIDER"
}

function print_bluetooth {
  device="n/a"
  # FIXME: blueoothctl just hangs if bluetooth.service isn't running
  if [[ "$(bluetoothctl info)" != "Missing device address argument" ]]; then
    device=$(bluetoothctl info | grep Name: | cut -d':' -f2)
  fi
  echo -e "Bl $device$DIVIDER"
}

function print_volume {
  vol_level=$( bc <<< "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -d' ' -f2)*100" | cut -d '.' -f1 )
  is_mute=$( wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep MUTED )
  if [[ ! -z "$is_mute" ]] ; then
    status=" M"
  else
    status=""
  fi
  echo -e "Vol $vol_level$status$DIVIDER"
}

function print_battery {
  batt_status=$( acpi -b | awk -F'[,:% ]' '{print $4}' )
  batt_charge=$( acpi -b | awk -F'[,:%]' '{print $3}' )
  if [[ $batt_status == "Charging" ]]; then
    batt_status=" C"
  else
    batt_status=""
  fi
  echo -e "Bat $batt_charge$batt_status$DIVIDER"
}

function print_date {
  echo -e "$( date +"%a %b %d %H:%M" )"
}

function print_status {
  status=""
  status+="$( print_network )"
  # status+="$( print_video )"
  status+="$( print_bluetooth )"
  status+="$( print_volume )"
  status+="$( print_battery )"
  status+="$( print_date )"
  status+="$SPACING"
  echo -e "$status"
}

case $1 in
  update-statusbar)
    # update statusbar
    xsetroot -name "$( print_status )"
	;;
  print)
    # print the status
    print_status
  ;;
esac
